steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/myimage:test', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/myimage:test']

  - name: 'google/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'pythonweb'
      - '--image=gcr.io/${PROJECT_ID}/myimage:test'
      - '--port=5000'
      - '--region=asia-northeast3  # 다른 리전으로 변경
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: "CLOUD_LOGGING_ONLY"
