steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/myimage:test', '.']
  
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/myimage:test']
  
  # Deploy to Cloud Run
  - name: 'google/cloud-sdk'
    args: 
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'pythonweb'
      - '--image=gcr.io/${PROJECT_ID}/myimage:test'
      - '--port=5000'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: "CLOUD_LOGGING_ONLY"  # 로그를 Cloud Logging에만 저장
  service_account: "your-service-account@your-project.iam.gserviceaccount.com"  # 서비스 계정 지정
